source 'https://rubygems.org'
ruby '2.0.0'
gem 'rails', '4.0.0'
gem 'rails-api'
gem 'pg'
gem 'redis'
gem 'rack-cache'
gem 'redis-rack-cache'
gem 'pry-rails'
gem 'httparty'
gem 'unicorn'
gem 'foreman'
gem 'rails_12factor'
gem 'newrelic_rpm'