source 'https://rubygems.org'
ruby '2.1.1'
gem 'rails', '4.0.3'
gem 'rails-api'
gem 'pg'
gem 'redis-store'
gem 'redis-rails'
gem 'rack-cache'
gem 'redis-rack-cache'
gem 'pry-rails'
gem 'httparty'
gem 'unicorn'
gem 'foreman'
gem 'rails_12factor'
gem 'newrelic_rpm'
gem 'rack-cors', require: 'rack/cors'
